<div class="row-fluid">
	<div class="span6 offset3"><div class="well">
		<ul class="nav nav-tabs" id="registerTabs">
			<li class="active"><a href="#registerBlogger" data-toggle="tab">Blogger</a></li>
	  		<li><a href="#registerAdvertiser" data-toggle="tab">Advertiser</a></li>
		</ul>
		<div class="tab-content">
			<div class="tab-pane active" id="registerBlogger">
				<?= $this->registerForm; ?>
			</div>
			<div class="tab-pane" id="registerAdvertiser">
				<?= $this->registerForm2; ?> 
			</div>
		</div>
	</div></div>
</div>